### ISSUE TITLE
Change .apk download for Get it on Github badge

### ISSUE THREAD

**Issue by inson1** [hobgoblina/oblique-strategies#3]

**Comment by hobgoblina** [comment]
I see that you're making similar requests on a lot of repos. Can I ask why?

**Comment by hobgoblina** [comment]
closing this for now. feel free to reply. I'm unlikely to do this without justification. Even tho I use github, I don't like it bc Microsoft is an awful company... so I don't really care about this unless it poses an acctual issue wrt accessibility/etc.
