### ISSUE TITLE
Typos on cards

### ISSUE THREAD

**Issue by 6b6279** [hobgoblina/oblique-strategies#6]
First of all, thanks a lot of the neat little app, I use the Oblique Strategies constantly during work. Before your app was available on F-Droid, I used to use https://stoney.sb.org/eno/oblique.html

I have noticed two typos over the last week using the app:
The card "Remember  .those quiet evenings" seems to be misformatted, it should read "Remember those quiet evenings"
The card "Slow preparation..Fast execution" also seems to be misformatted, it should read "Slow preparation... Fast execution"

Also, the empty card is missing. The original Oblique Strategies deck contains one blank card.

I could submit a pull request, but I guess it'd be faster for you to make the changes.

Thanks once again for the neat app!

**Comment by hobgoblina** [comment]
I do have an actual 5th edition deck, and both of the cards you referenced are printed the way they are in the app. I've actually looked for other examples of those cards online to make sure mine weren't misprinted, and every one I've found looks the same — I think I was even able to confirm that they were like that in older editions as well. I'm trying to replicate the cards as accurately as possible, so I kept them as they are now. That said, I'm very curious about the history/intention behind thise cards, so if you come across any info plz lemme know! And I would def be down to change them, but only if there's a more official source (I guess Eno? lol) saying I should.

For the blank card, do you know for sure if they were included in editions 1-3 or 5? I don't have one in my deck, but I saw it referenced in some lists of cards. A "blank" card was included in the 4th edition that was illustrated by Pae White (blank as in no text, but did include graphics). The more I dug into it, it seemed like the lists that mentioned a blank card were likely referring to that... many of them even said stuff like "(blank graphic card)" or "(blank card illustrated by Pae White)". Despite that, I was still on the fence a bit about including a blank card, so I could probably be convinced.

**Comment by 6b6279** [comment]
I have assumed that those two cards had typos because in the card list of the 4th ed. (http://www.rtqe.net/ObliqueStrategies/Ed4.html), those cards are actually formatted differently. Although in true Eno fashion I can imagine that the person that composed the card list also assumed that those were typos and "corrected" them.

Regarding the blank card, I only know that it was included in the 4th edition. And I couldn't find a picture of the blank card anyway.

If you have a physical deck, I would be very interested to see a picture of the "Remember .those quiet evenings" card. I can't imagine how that looks in print with botched formatting.

**Comment by hobgoblina** [comment]
yeah the 4th edition deck is a unique deck... it was commissioned in 1996 by Peter Norton (as in Norton Antivirus), because his family commissions small artworks each year to send out as christmas cards. Pae White designed the cards. the strategies were translated into 5 other languages (Mandarin, Hindi, Spanish, Russian and Arabic) which were all included on each card, and the wording on some of the strategies was altered a bit.

i'm trying to get my hands on a deck but they're a bit rare and can be costly. I plan on reaching out to Pae for permission to publish high-res scans, and hope to include a setting to switch between decks.

but also, because of its uniqueness, I didn't include any of the altered strategy wordings/etc. in the current version.

**Comment by hobgoblina** [comment]
here's pics of the two cards you mentioned... I pulled these from the Oblique Strategies mastodon bot @oblique_strategies@botsin.space

![original](https://github.com/hobgoblina/oblique-strategies/assets/20880695/9f081cea-2b60-4065-9dfa-e753c05ae6c3)
![original](https://github.com/hobgoblina/oblique-strategies/assets/20880695/093afe20-9008-4632-bd79-7ea8b18a59ab)

**Comment by 6b6279** [comment]
Thanks a lot for the pictures and the informative answer. I'll close the issue now.
